[tool.poetry]
name = "poggychat"
version = "0.0.1"
description = "Fully Open Source Chatting App & Server"
authors = ["MisileLaboratory"]
license = "MisileLab License"

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.19.2"
tomli = "^1.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
